<?php

namespace Briooz\TaskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriaDeducibleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaDeducibleRepository extends EntityRepository
{
}
