<?php

namespace Briooz\TaskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstadoProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoProductoRepository extends EntityRepository
{
}
