# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: BrioozTaskBundle:Usuario
                property: usuario

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
                # field names for the username and password fields:
                username_parameter: _usuario
                password_parameter: _password
                # default_target_path: default_security_target
                # always_use_default_target_path: true
            logout:
                path:   /logout
                target: /login
        
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
        
    encoders:
        Briooz\TaskBundle\Entity\Usuario:
            algorithm: bcrypt
            cost: 12
    
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, roles: IS_AUTHENTICATED_FULLY }        